---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: lxd

lint:
  name: yamllint
  options:
    config-file: ${DEV_MOLECULE_RULES}/yaml-lint.yml

platforms:
  - name: Plex-CentOS7
    source:
      alias: centos/7/amd64

  - name: Plex-Debian9
    source:
      alias: debian/stretch/amd64

  - name: Plex-Fedora29
    source:
      alias: fedora/29/amd64

  - name: Plex-Fedora28
    source:
      alias: fedora/28/amd64

  - name: Plex-Ubuntu1804
    source:
      alias: ubuntu/bionic/amd64

  - name: Plex-Ubuntu1604
    source:
      alias: ubuntu/xenial/amd64

  - name: Plex-Ubuntu1404
    source:
      alias: ubuntu/trusty/amd64

provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  lint:
    name: ansible-lint
    options:
      c: ${DEV_MOLECULE_RULES}/ansible-lint.yml

verifier:
  name: goss
  lint:
    name: yamllint
    options:
      config-file: ${DEV_MOLECULE_RULES}/yaml-lint.yml

scenario:
  name: default
