---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: lxd

lint:
  name: yamllint
  options:
    config-file: ${DEV_MOLECULE_RULES}/yaml-lint.yml

platforms:
  - name: Plex-CentOS7
    source:
      alias: centos/7/amd64

  - name: Plex-CentOS6
    source:
      alias: centos/6/amd64
    config:
      limits.kernel.memlock: 60397977:60397977

  - name: Plex-Debian9
    source:
      alias: debian/stretch/amd64

  - name: Plex-Fedora27
    source:
      alias: fedora/27/amd64
    config:
      limits.kernel.memlock: 60397977:60397977

  - name: Plex-Fedora26
    source:
      alias: fedora/26/amd64
    config:
      limits.kernel.memlock: 60397977:60397977

# TODO: Not yet released
#  - name: Plex-Ubuntu1804
#    alias: ubuntu/bionic/amd64

  - name: Plex-Ubuntu1604
    source:
      alias: ubuntu/xenial/amd64

  - name: Plex-Ubuntu1404
    source:
      alias: ubuntu/trusty/amd64

provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  lint:
    name: ansible-lint
    options:
      c: ${DEV_MOLECULE_RULES}/ansible-lint.yml

verifier:
  name: goss
  lint:
    name: yamllint
    options:
      config-file: ${DEV_MOLECULE_RULES}/yaml-lint.yml

scenario:
  name: default
