---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-plex

  post_tasks:
    - name: Test Plex webinterface
      uri:
        url: "http://{{ inventory_hostname }}:32400/web"

    - name: Wait for Tautulli to succesfully restart
      wait_for:
        port: 8181
      when: tautulli_install

    - name: Test Tautulli webinterface
      uri:
        url: "http://{{ inventory_hostname }}:8181/home"
      when: tautulli_install
